# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainproto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmainproto.proto\"\x17\n\x07MapText\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1a\n\tMapNumber\x12\r\n\x05value\x18\x01 \x01(\x05\"\x14\n\x04Text\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1a\n\nReduceText\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1d\n\x0cReduceNumber\x12\r\n\x05value\x18\x01 \x01(\x05\x32O\n\x0emasterFunction\x12\x1d\n\tnewServer\x12\x05.Text\x1a\x07.Number\"\x00\x12\x1e\n\x0c\x66\x65tchServers\x12\x05.Text\x1a\x05.Text\"\x00\x32\x30\n\x0bmapFunction\x12!\n\x07mapWord\x12\x08.MapText\x1a\n.MapNumber\"\x00\x32\x39\n\x0ereduceFunction\x12\'\n\x07redWord\x12\x0b.ReduceText\x1a\r.ReduceNumber\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mainproto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPTEXT._serialized_start=19
  _MAPTEXT._serialized_end=42
  _MAPNUMBER._serialized_start=44
  _MAPNUMBER._serialized_end=70
  _TEXT._serialized_start=72
  _TEXT._serialized_end=92
  _NUMBER._serialized_start=94
  _NUMBER._serialized_end=117
  _REDUCETEXT._serialized_start=119
  _REDUCETEXT._serialized_end=145
  _REDUCENUMBER._serialized_start=147
  _REDUCENUMBER._serialized_end=176
  _MASTERFUNCTION._serialized_start=178
  _MASTERFUNCTION._serialized_end=257
  _MAPFUNCTION._serialized_start=259
  _MAPFUNCTION._serialized_end=307
  _REDUCEFUNCTION._serialized_start=309
  _REDUCEFUNCTION._serialized_end=366
# @@protoc_insertion_point(module_scope)
